replicaCount: 1

image:
  repository: akshay2001a/nodejs-app
<<<<<<< HEAD
<<<<<<< HEAD
  tag: "22"
=======
  tag: "22"
>>>>>>> 66a95bc (tag update 1)
=======
  tag: "21"
>>>>>>> fc6b317 (updated 2)
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30007

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: nodejs-app.local
      paths: ["/"]
  tls: []

resources: {}
