apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- gitrepository.yaml
- helmrelease.yaml
- image-repository.yaml
- image-policy.yaml
- image-update-automation.yaml
