---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: nodejs-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nodejs-app
  policy:
    semver:
      range: 5.0.x
